"""initial schema - six tables

Revision ID: 6e00987c7dbb
Revises: 
Create Date: 2026-03-18 20:49:09.004771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e00987c7dbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_schedule', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watch_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('threshold_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retailer_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_query_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['watch_query_id'], ['watch_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_query_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['watch_query_id'], ['watch_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailer_url_id', sa.Integer(), nullable=False),
    sa.Column('scrape_job_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('listing_url', sa.String(length=2048), nullable=False),
    sa.Column('retailer_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_url_id'], ['retailer_urls.id'], ),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_result_id', sa.Integer(), nullable=False),
    sa.Column('watch_query_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_result_id'], ['scrape_results.id'], ),
    sa.ForeignKeyConstraint(['watch_query_id'], ['watch_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed default app_settings row
    op.execute("INSERT INTO app_settings (id, default_schedule) VALUES (1, 'daily')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('scrape_results')
    op.drop_table('scrape_jobs')
    op.drop_table('retailer_urls')
    op.drop_table('watch_queries')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
